version: '3.8'
services:
  postgres_db:
    image: postgres:16-bookworm
    container_name: PostgresCont3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - '5435:5432'
    volumes:
      - ~/docker/postgres3/data:/var/lib/postgresql/data