version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresCont
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - '5433:5432'
    volumes:
      - /Users/satvik.nema/docker/postgres/data:/var/lib/postgresql/data