name: py

on:
  workflow_dispatch
#  pull_request:
#    types:
#      - opened
#      - reopened
#      - synchronize

permissions:
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: execute py script
        run: |
          python .github/workflows/my_file.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }} # in case of an issue/comment/review, this will no longer be a PR number, but an ID associated with that particular event!